<?php

$cminds_plugin_config = array(
    'plugin-is-pro' => TRUE,
    'plugin-has-addons' => FALSE,
    'plugin-version' => com\cminds\searchwidget\App::VERSION,
    'plugin-abbrev' => com\cminds\searchwidget\App::SLUG,
    'plugin-short-slug' => com\cminds\searchwidget\App::SLUG,
    'plugin-parent-short-slug' => '',
    'plugin-affiliate' => '',
    'plugin-show-guide' => FALSE,
    'plugin-guide-text' => '<p>The description of the plugin goes here</p>',
    'plugin-guide-video-height' => 180,
    'plugin-guide-videos' => array(
//        array('title' => 'Video #1 title', 'video_id' => '134490629'),
//        array('title' => 'Video #2 title', 'video_id' => '134490629'),
//        array('title' => 'Video #3 title', 'video_id' => '134490629'),
    ),
    'plugin-redirect-after-install' => admin_url('admin.php?page=cm-search-widget'),
    'plugin-file' => com\cminds\searchwidget\App::PLUGIN_FILE,
    'plugin-dir-path' => plugin_dir_path(com\cminds\searchwidget\App::PLUGIN_FILE),
    'plugin-dir-url' => plugin_dir_url(com\cminds\searchwidget\App::PLUGIN_FILE),
    'plugin-basename' => plugin_basename(com\cminds\searchwidget\App::PLUGIN_FILE),
    'plugin-icon' => '',
    'plugin-name' => com\cminds\searchwidget\App::PLUGIN_NAME_EXTENDED,
    'plugin-license-name' => com\cminds\searchwidget\App::PLUGIN_NAME_EXTENDED,
    'plugin-slug' => '',
    'plugin-menu-item' => com\cminds\searchwidget\App::SLUG,
    'plugin-textdomain' => com\cminds\searchwidget\App::SLUG,
    'plugin-userguide-key' => '',
    'plugin-store-url' => 'https://www.cminds.com/store/',
    'plugin-support-url' => '',
    'plugin-review-url' => '',
    'plugin-changelog-url' => 'https://www.cminds.com/store/',
    'plugin-licensing-aliases' => array(com\cminds\searchwidget\App::PLUGIN_NAME_EXTENDED),
);
